### ISSUE TITLE
"Unsupported option" sshd_config errors on container start

### ISSUE THREAD

**Issue by polendri** [jgiannuzzi/docker-gitolite#7]
Using image 0fd0cb87b4cd, when I start the container I get the following errors in the logs and the container immediately exits:

```
/etc/ssh/sshd_config line 65: Unsupported option KerberosAuthentication
/etc/ssh/sshd_config line 71: Unsupported option GSSAPIAuthentication
```

I'm having a hard time debugging it. I've been running this thing for a while now with no issues, but it has been months since I've last pulled down an image. Anyone know what might be happening?

**Comment by jgiannuzzi** [comment]
Thanks for reporting this, @pshendry!

It has been fixed in the latest release.

**Comment by polendri** [comment]
Thanks for the quick fix, much appreciated!
